sudo: required
services: 
    - docker

before_install:
    - docker build -t jasonsb/goodstart-auth:dev -f Dockerfile.dev .

script:
    - docker run --env-file .env jasonsb/goodstart-auth:dev npm run test -- --coverage