services: 
    - docker

language: node_js
node_js:
    - "13.1.0"
  
os: linux

  

before_install:
    - docker build -t jasonsb/goodstart-auth:dev -f Dockerfile.dev .

script:
    - docker run --env ACCESS_TOKEN_EXPIRES_IN = $ACCESS_TOKEN_EXPIRES_IN --env ACCESS_TOKEN_SECRET = $ACCESS_TOKEN_SECRET --env DB_CONNECTION_URL = $DB_CONNECTION_URL --env PORT = $PORT --env REFRESH_TOKEN_EXPIRES_IN = $REFRESH_TOKEN_EXPIRES_IN --env REFRESH_TOKEN_SECRET = $REFRESH_TOKEN_SECRET --env USE_DB_CONNECTION_URL = $USE_DB_CONNECTION_URL jasonsb/goodstart-auth:dev npm run test -- --coverage   