services: 
    - docker

language: node_js
node_js:
    - "13.1.0"
  
os: linux

before_install:
    - docker build -t jasonsb/goodstart-auth:dev -f Dockerfile.dev .

script:
    - docker run --env-file .env jasonsb/goodstart-auth:dev npm run test -- --coverage